export * from './RegistrationForm/RegistrationForm';
export * from './Button/Button';
export * from './LoginForm/LoginForm';
export * from './Background/Background';
export * from './Box/Box';
export * from './Input/Input';
export * from './Icon/Icon';
export * from './Logo/Logo';
export * from './AnimationLogin/AnimationLogin';
